/**
 * How much page an airline earns, and whether it is indexed at all.
 *
 * This replaces `airlineIsSubstantive()`, which gated on the presence of the
 * CMS `about` field. That test stopped discriminating the moment the enrichment
 * pass wrote an `about` onto 1,019 of the 1,096 airlines: every page satisfied
 * the gate at once and the directory began admitting itself to the sitemap —
 * GDS vendors and carriers that have not flown in years included. A gate that
 * generated text can open is not a gate.
 *
 * Tiering keys off data the page can point at instead:
 *   - route-network facts derived from TravelPayouts (data/route-facts/all.json)
 *   - the ingested review store (content/airline-reviews/)
 *   - routes tracked in Strapi, which the page renders as real route cards
 *
 * None of those can be satisfied by writing prose, which is the property the
 * old gate lost.
 *
 * Tier 3 pages stay live and stay linked — /airlines lists every carrier — they
 * just carry `noindex, follow` and stay out of the sitemap.
 */
import type { StrapiAirline } from '@/lib/strapi';
import { getRouteFacts } from '@/lib/route-facts';
import { hasAirlineReviews } from '@/lib/airline-reviews';

/** 1 = full treatment, 2 = data modules only, 3 = directory row only. */
export type AirlineTier = 1 | 2 | 3;

/** Destinations a carrier must serve to earn the full Tier 1 treatment. */
export const TIER1_MIN_DESTINATIONS = 80;

/**
 * A smaller network still earns Tier 1 when the carrier also has ingested
 * reviews — that pairing gives the page first-party material no template can
 * produce.
 */
export const TIER1_REVIEWED_MIN_DESTINATIONS = 40;

/** Below this a carrier has too little network to describe. Tunable knob. */
export const TIER2_MIN_DESTINATIONS = 5;

/**
 * Airline guides that have passed the sourced-content publication gate.
 *
 * The directory-wide AIRLINES_INDEXABLE switch remains off while the rebuild
 * continues. This allowlist lets reviewed guides use the Tier 1 template,
 * become indexable, and enter the sitemap without exposing hundreds of thin
 * directory entries at the same time.
 */
export const PUBLISHED_AIRLINE_GUIDES = new Set([
  'abx-air-inc',
  'adria-airways',
  'aegean-airlines',
  'aer-lingus',
  'aero-charter-ukraine',
  'aero-mongolia',
  'aero-tropics-air-services',
  'aeroflot',
  'aeromar',
  'aeromexico',
  'african-express-airways',
  'ahk-air-hong-kong-limited',
  'aigle-azur',
  'air-albania',
  'air-alsie',
  'air-arabia',
  'air-arabia-egypt',
  'air-arabia-maroc',
  'air-astana',
  'air-austral',
  'air-botswana',
  'air-burkina',
  'air-busan',
  'air-cambodia',
  'air-canada',
  'air-cargo-carriers-llc',
  'air-changan',
  'air-china',
  'air-corsica',
  'air-cote-divoire',
  'air-dilijans',
  'air-djibouti',
  'air-europa',
  'air-france',
  'air-greenland',
  'air-iceland-connect',
  'air-india',
  'air-india-express',
  'air-japan',
  'air-kiribati',
  'air-koryo',
  'air-libya',
  'air-macau',
  'air-madagascar',
  'air-mauritius',
  'air-mekong',
  'air-moana',
  'air-moldova',
  'air-namibia',
  'air-new-zealand',
  'air-niamey',
  'air-niugini',
  'air-north',
  'air-nostrum',
  'air-rarotonga',
  'air-saint-pierre',
  'air-serbia',
  'air-seychelles',
  'air-tahiti',
  'air-tahiti-nui',
  'air-tanzania',
  'air-thanlwin',
  'air-tindi',
  'air-transat',
  'air-transport-international-llc',
  'air-vanuatu',
  'air-zimbabwe',
  'airasia',
  'airasia-x',
  'airbaltic',
  'airblue',
  'airbridgecargo',
  'aircalin',
  'airkenya',
  'airline-urga',
  'airlink',
  'airnorth',
  'ajet',
  'aklak-air',
  'alaska-airlines',
  'all-nippon-airways',
  'allegiant-air',
  'almasria-universal-airlines',
  'amakusa-airlines',
  'american-airlines',
  'amerijet-international-inc',
  'ana-wings',
  'ariana-afghan-airlines',
  'arik-air',
  'arkia',
  'aserca-airlines',
  'asiana-airlines',
  'asl-airlines-france',
  'atlantic-airways',
  'atlas-air',
  'atran',
  'austrian-airlines',
  'avianca',
  'avianca-costa-rica',
  'avianca-ecuador',
  'aviastar-tu',
  'avion-express-lithuania',
  'avion-express-malta',
  'azerbaijan-airlines',
  'bangkok-airways',
  'batik-air',
  'bearskin-airlines',
  'beijing-capital-airlines',
  'bemidji-airlines',
  'bering-air',
  'berjaya-air',
  'bhutan-airlines',
  'binter-canarias',
  'blue-air',
  'blue-islands',
  'blue1',
  'boliviana-de-aviacion',
  'breeze-airways',
  'brit-air',
  'british-airways',
  'brussels-airlines',
  'buddha-air',
  'bvi-airways',
  'cabo-verde-airlines',
  'calm-air',
  'canadian-north',
  'carpatair',
  'cathay-pacific',
  'cayman-airways',
  'cebu-pacific',
  'ceiba-intercontinental',
  'central-mountain-air',
  'chautauqua-airlines',
  'chengdu-airlines',
  'china-airlines',
  'china-cargo-airlines',
  'china-eastern',
  'china-express-airlines',
  'china-southern-airlines',
  'china-united-airlines',
  'chongqing-airlines',
  'cimber',
  'citilink',
  'conviasa',
  'copa-airlines',
  'corendon-airlines',
  'corendon-airlines-europe',
  'corsair-international',
  'croatia-airlines',
  'cronos-airlines',
  'csa-czech-airlines',
  'cyprus-airways',
  'daallo-airlines',
  'dana-air',
  'delta-air-lines',
  'dhl-air-limited',
  'dniproavia',
  'donavia',
  'donghai-airlines',
  'dot-lt',
  'eastar-jet',
  'eastern-airways',
  'easyjet',
  'edelweiss-air',
  'egyptair',
  'emirates',
  'envoy-air',
  'eritrean-airlines',
  'ethiopian-airlines',
  'etihad-airways',
  'euroatlantic-airways',
  'european-air-charter',
  'eurowings',
  'eva-air',
  'everts-air-cargo',
  'expressjet',
  'fat-far-eastern-air-transport',
  'fedex',
  'fiji-airways',
  'finnair',
  'firefly',
  'first-air',
  'flybe',
  'flydubai',
  'frontier-airlines',
  'garuda-indonesia',
  'georgian-airways',
  'globus-airlines',
  'gojet-airlines',
  'gol-transportes-aereos',
  'grand-canyon-scenic-airlines',
  'grand-china-air',
  'great-lakes-airlines',
  'gulf-air',
  'hainan-airlines',
  'halcyonair',
  'hawaiian-airlines',
  'hawkair',
  'heli-air-monaco',
  'helijet',
  'helvetic-airways',
  'hk-express',
  'hong-kong-airlines',
  'horizon-air',
  'hunnu-air',
  'iberia',
  'iberia-express',
  'ibex-airlines',
  'icelandair',
  'indigo',
  'intercaribbean-airways',
  'iraero',
  'iraqi-airways',
  'israir-airlines',
  'ita-airways',
  'izhavia',
  'japan-air-commuter',
  'japan-airlines',
  'japan-transocean-air',
  'jazeera-airways',
  'jeju-air',
  'jet-airways',
  'jet-asia-airways',
  'jet-aviation-business',
  'jet2com',
  'jetblue',
  'jetstar',
  'jetstar-asia',
  'jetstar-japan',
  'jordan-aviation',
  'kalitta-air',
  'kam-air',
  'kan-air',
  'kartika-airlines',
  'kenmore-air',
  'kenn-borek-air',
  'kenya-airways',
  'klm-cityhopper',
  'klm-royal-dutch-airlines',
  'korean-air',
  'kunming-airlines',
  'kuwait-airways',
  'la-compagnie',
  'lam-mozambique-airlines',
  'lan-chile-cargo',
  'lao-airlines',
  'laser-airlines',
  'latam-airlines',
  'latam-airlines-colombia',
  'latam-airlines-ecuador',
  'latam-airlines-paraguay',
  'latam-airlines-peru',
  'libyan-airlines',
  'lion-air',
  'loganair',
  'lot-polish',
  'lucky-air',
  'lufthansa',
  'lufthansa-cityline',
  'luxair',
  'lynden-air-cargo-llc',
  'mahan-air',
  'malaysia-airlines',
  'maldivian',
  'mango',
  'martinair',
  'maya-island-air',
  'miat-mongolian-airlines',
  'middle-east-airlines',
  'mng-airlines',
  'montenegro-airlines',
  'motor-sich-airlines',
  'myanmar-airways-international',
  'national-airlines',
  'nauru-airlines',
  'neos',
  'nile-air',
  'nippon-cargo-airlines',
  'nok-air',
  'nordwind-airlines',
  'norse-atlantic-uk',
  'northern-air-cargo',
  'northwest-airlines',
  'northwestern-air',
  'norwegian-air-sweden',
  'nouvelair',
  'nova-airlines',
  'okay-airways',
  'olympic-air',
  'oman-air',
  'onur-air',
  'orient-thai-airlines',
  'pacific-airlines',
  'pacific-coastal-airlines',
  'pal-express',
  'pascan-aviation',
  'pegasus-airlines',
  'philippine-airlines',
  'png-air',
  'polar-air-cargo-worldwide-inc',
  'primera-air',
  'proflight-zambia',
  'qantas',
  'qatar-airways',
  'regional-air',
  'rex-regional-express',
  'rossiya-airlines',
  'royal-air-maroc',
  'royal-brunei-airlines',
  'royal-jordanian',
  'rusline',
  'rwandair',
  'ryanair',
  'safi-airways',
  'sansa',
  'sas-scandinavian',
  'sata-air-acores',
  'saudia',
  'scat',
  'scoot',
  'sepehran-airlines',
  'severstal-air-company',
  'shaheen-air',
  'shandong-airlines',
  'shanghai-airlines',
  'shenzhen-airlines',
  'sichuan-airlines',
  'silkair',
  'silver-airways',
  'singapore-airlines',
  'sky-airline',
  'sky-airlines',
  'sky-angkor-airlines',
  'skybahamas',
  'skymark-airlines',
  'skyward-airlines',
  'skywest-airlines',
  'solaseed-air',
  'solomon-airlines',
  'somon-air',
  'south-african-airways',
  'southern-air',
  'southern-airways-express',
  'southwest-airlines',
  'spicejet',
  'spirit-airlines',
  'spring-japan',
  'srilankan-airlines',
  'sriwijaya-air',
  'starlux-airlines',
  'sudan-airways',
  'sun-air',
  'sunclass-airlines',
  'sundair',
  'sunexpress',
  'sunexpress-deutschland',
  'sunrise-airways',
  'sunwing-airlines',
  'suparna-airlines',
  'surinam-airways',
  'swiss',
  'swoop',
  'sylt-air-gmbh',
  'taag-angola',
  'tailwind-airlines',
  'tajik-air',
  'tame',
  'tandem-aero',
  'tap-air-portugal',
  'taquan-air',
  'tarco-aviation',
  'tatarstan-airlines',
  'thai-airasia',
  'thai-airasia-x',
  'thai-airways',
  'thai-lion-air',
  'thai-smile',
  'thai-vietjet-air',
  'thomas-cook-airlines',
  'thomas-cook-airlines-belgium',
  'tianjin-airlines',
  'tigerair-mandala',
  'titan-airways-limited',
  'trade-air',
  'transavia',
  'transavia-france',
  'trigana-air-service',
  'trip-linhas-aereas',
  'tui-airways',
  'tui-fly-deutschland',
  'tunisair',
  'tunisair-express',
  'turkish-airlines',
  'turkmenistan-airlines',
  'tway-air',
  'uls-airlines-cargo',
  'uni-air',
  'uni-top-airlines',
  'united-airlines',
  'ural-airlines',
  'urumqi-air',
  'us-bangla-airlines',
  'uzbekistan-airways',
  'valuejet',
  'vieques-air-link',
  'vietjet',
  'vietnam-airlines',
  'vim-airlines',
  'virgin-america',
  'virgin-atlantic',
  'virgin-australia',
  'vistara',
  'viva-aerobus',
  'vladivostok-air',
  'vlm-airlines',
  'voepass-linhas-aereas',
  'volaris',
  'volga-dnepr-airlines',
  'vueling',
  'wamos-air',
  'warbelows-air',
  'west-air',
  'westjet',
  'westjet-encore',
  'white-airways',
  'wideroe',
  'winair',
  'windrose-airlines',
  'wizz-air',
  'wow-air',
  'xiamen-airlines',
  'yakutia-airlines',
  'yamal-airlines',
  'yemenia',
  'yeti-airlines',
  'zimex-aviation',
]);

export function airlineGuideIsPublished(slug: string): boolean {
  return PUBLISHED_AIRLINE_GUIDES.has(slug);
}

export type AirlineTierInput = Pick<StrapiAirline, 'slug' | 'iataCode'>;

/**
 * `hasTrackedRoutes` is supplied by the caller, matching the old gate: the page
 * passes `routes.length > 0`, the sitemap passes route-coverage set membership
 * (see fetchRouteCoverage).
 */
export function airlineTier(a: AirlineTierInput, hasTrackedRoutes: boolean): AirlineTier {
  const destinations = getRouteFacts(a.iataCode)?.destinationCount ?? 0;

  if (destinations >= TIER1_MIN_DESTINATIONS) return 1;
  if (destinations >= TIER1_REVIEWED_MIN_DESTINATIONS && hasAirlineReviews(a.slug)) return 1;
  if (destinations >= TIER2_MIN_DESTINATIONS || hasTrackedRoutes) return 2;
  return 3;
}

/**
 * Indexable, and eligible for the sitemap.
 *
 * Reviews alone deliberately do NOT lift a carrier out of Tier 3. 75 carriers
 * have ingested reviews but no route data at all, and reviews outlive
 * operations — several of those look like airlines that stopped flying after
 * the reviews were written. They stay out of the index until an operating
 * status is recorded against them rather than inferred here.
 */
export function airlineIsIndexable(a: AirlineTierInput, hasTrackedRoutes: boolean): boolean {
  return airlineTier(a, hasTrackedRoutes) < 3;
}
